<a href="https://colab.research.google.com/github/zaitmi002/ml-ai/blob/main/day2_numpy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]


In [ ]:
sum1=list1+list2

In [ ]:
sum1

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
sum_l=[]

In [ ]:
for num1,num2, in zip(list1,list2):
  sum_l.append(num1+num2)

In [ ]:
sum_l

[6, 8, 10, 12]

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
arr1=np.array(list1)

In [ ]:
arr1

array([1, 2, 3, 4])

In [ ]:
arr2=np.array(list2)

In [ ]:
arr2

array([5, 6, 7, 8])

In [ ]:
sum_l1=arr1+arr2

In [ ]:
sum_l1

array([ 6,  8, 10, 12])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
list3=[[2,3,4,],
       [5,6,8]]

In [ ]:
arr3=np.array(list3)

In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(2, 3)

In [ ]:
arr4=np.arange(6)

In [ ]:
arr4

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr5=arr4.reshape(2,3)

In [ ]:
arr5

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr4.sum()

15

In [ ]:
arr4.mean()

2.5

In [ ]:
np.sqrt(arr5)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.rand(3,4)

array([[0.99365639, 0.07707079, 0.46168758, 0.44467545],
       [0.49620716, 0.51656861, 0.93280857, 0.36918259],
       [0.48239124, 0.79483009, 0.12532689, 0.46743609]])

# **PANDAS**

In [ ]:
import pandas as pd

In [ ]:
data1=pd.read_csv('/content/auto-mpg.csv')